using BusDriver.Core.Data;
using UnityEngine;

namespace BusDriver.Gameplay.Views {
    // The PR #5 capsule body, generated by PrefabBuilder: a body capsule and a head sphere with a
    // face bar, posed seated (at the wheel) or standing (on foot).
    public sealed class GreyboxPlayerAvatarView : PlayerAvatarViewBase {
        [SerializeField] Transform body;
        [SerializeField] Transform head;
        [SerializeField] PassengerPose pose = PassengerPose.Standing;

        // The MVP numbers: root at the feet (standing) or the seat surface (seated)
        static readonly Vector3 StandingBodyPos = new Vector3(0f, 0.75f, 0f);
        static readonly Vector3 StandingBodyScale = new Vector3(0.42f, 0.75f, 0.42f);
        static readonly Vector3 StandingHeadPos = new Vector3(0f, 1.6f, 0f);
        static readonly Vector3 SeatedBodyPos = new Vector3(0f, 0.42f, 0f);
        static readonly Vector3 SeatedBodyScale = new Vector3(0.42f, 0.42f, 0.42f);
        static readonly Vector3 SeatedHeadPos = new Vector3(0f, 0.94f, 0f);

        public PassengerPose Pose { get { return pose; } }

        void Awake() {
            SetPose(pose);
        }

        public override void SetPose(PassengerPose next) {
            pose = next;
            bool seated = pose == PassengerPose.Seated;
            if (body != null) {
                body.localPosition = seated ? SeatedBodyPos : StandingBodyPos;
                body.localScale = seated ? SeatedBodyScale : StandingBodyScale;
            }
            if (head != null) {
                head.localPosition = seated ? SeatedHeadPos : StandingHeadPos;
            }
        }

        // The greybox has no walk cycle
        public override void SetLocomotion(float metresPerSecond) {
        }

        public override void SetVisible(bool visible) {
            gameObject.SetActive(visible);
        }
    }
}
