using BusDriver.Core.Data;
using UnityEngine;

namespace BusDriver.Gameplay.Views {
    // The greybox passenger (§4.14): today's capsule-and-sphere poses plus one primitive effect per
    // tell, generated by PrefabBuilder as View_GreyboxPassenger and coloured per look by ViewFactory.
    // Root at the feet (standing) or on the seat cushion (seated), +Z forward. Parts are hidden by
    // switching their GameObjects; Renderer.enabled belongs to RendererFlicker.
    //
    // Tell → effect (intensity 0–1):
    //   HeadTrack       the head turns toward the SetLookAt target (25°/s, yaw ±110°, pitch ±35°,
    //                   the MVP StaringMonster math); weight = max(look weight, HeadTrack)
    //   Stillness       idle breathing bob × (1 − intensity)
    //   EyesWide        two white eyes, scale 0 → 0.06
    //   WhisperLean     body roll up to 12° toward the look target's side (+x without a target)
    //   MouthWhisper    jitter on the mouth box
    //   JawStretch      the mouth box stretched up to ×3
    //   MimicFlicker    forwarded to RendererFlicker (renderer blinking)
    //   MimicReveal     body and head tinted red, plus RendererFlicker's fast strobe
    //   TelegraphStand  the standing pose with a 15° forward lean
    //   AngelWeep       head pitched down 35°, the arm boxes raised to the face
    //   AngelReach      the arm boxes swing from the sides to straight forward
    //   DecoyNodOff     head pitched down 40°
    //   DecoyPhoneGlow  an emissive quad in front of the face, pulsing
    //   DecoyMutter     mouth jitter
    //   DecoyFacingBackwards  the view turned 180°
    //   DecoyHoodUp     a dark cone over the head
    //   None            no-op
    public sealed class GreyboxPassengerView : PassengerViewBase {
        // The MVP numbers: root at the feet (standing) or the seat surface (seated)
        static readonly Vector3 StandingBodyPos = new Vector3(0f, 0.75f, 0f);
        static readonly Vector3 StandingBodyScale = new Vector3(0.42f, 0.75f, 0.42f);
        static readonly Vector3 StandingHeadPos = new Vector3(0f, 1.62f, 0f);
        static readonly Vector3 SeatedBodyPos = new Vector3(0f, 0.42f, 0f);
        static readonly Vector3 SeatedBodyScale = new Vector3(0.42f, 0.42f, 0.42f);
        static readonly Vector3 SeatedHeadPos = new Vector3(0f, 0.94f, 0f);
        const float StandingShoulderY = 1.38f;
        const float SeatedShoulderY = 0.72f;

        const float HeadTurnSpeed = 25f;
        const float YawLimit = 110f;
        const float PitchLimit = 35f;
        const float BobAmplitude = 0.008f;
        const float BobHz = 0.25f;
        const float WalkBobAmplitude = 0.025f;
        const float WalkBobHz = 2f;
        const float MaxLean = 12f;
        const float TelegraphLean = 15f;
        const float NodPitch = 40f;
        const float WeepPitch = 35f;
        const float MaxEyeScale = 0.06f;
        const float MouthJitter = 0.006f;
        const float TurnHoldSeconds = 0.6f;
        const float FlinchSeconds = 0.18f;
        const float LookAroundSeconds = 1.2f;
        const float DeathSeconds = 0.5f;
        static readonly Color RevealRed = new Color(0.9f, 0.05f, 0.05f);
        static readonly Color PhoneGlow = new Color(0.55f, 0.75f, 1f);

        [Header("Parts (PrefabBuilder)")]
        [SerializeField] Transform rig;
        [SerializeField] Transform bodyPivot;
        [SerializeField] Transform body;
        [SerializeField] Transform headPivot;
        [SerializeField] Transform face;
        [SerializeField] Transform eyes;
        [SerializeField] Transform mouth;
        [SerializeField] GameObject hood;
        [SerializeField] Renderer phone;
        [SerializeField] Transform shoulders;
        [SerializeField] Transform armLeft;
        [SerializeField] Transform armRight;
        [SerializeField] Renderer[] bodyRenderers = new Renderer[0];
        [SerializeField] Renderer[] headRenderers = new Renderer[0];

        [Header("Accessories, in LookAccessory order from Cap")]
        [SerializeField] GameObject[] accessories = new GameObject[0];

        [SerializeField] PassengerPose pose = PassengerPose.Standing;
        // The look's colours, kept serialized: property blocks aren't saved with a scene (the menu
        // figure is configured at build time)
        [SerializeField] Color bodyColor = new Color(0.65f, 0.55f, 0.5f);
        [SerializeField] Color headColor = new Color(0.8f, 0.68f, 0.58f);
        [SerializeField] string lookId = "";
        [SerializeField] float bobPhase;

        // Tell intensities, indexed by slot (see Slot)
        readonly float[] tells = new float[16];
        Transform lookTarget;
        float lookWeight;
        Quaternion headTrack = Quaternion.identity;
        float locomotion;
        MaterialPropertyBlock block;
        System.Random jitter;
        float turnHoldUntil = -1f;
        float flinchUntil = -1f;
        float lookAroundStart = -1f;
        float deathStart = -1f;
        bool revealTinted;
        RendererFlicker flicker;
        Vector3 mouthRestPos;
        Vector3 mouthRestScale;
        bool captured;

        public override Transform Head { get { return headPivot; } }
        public override Transform Face { get { return face; } }
        public PassengerPose Pose { get { return pose; } }
        public string LookId { get { return lookId; } }

        void Awake() {
            Capture();
            ApplyColours(0f);
            SetPose(pose);
        }

        void Capture() {
            if (captured) {
                return;
            }
            captured = true;
            block = new MaterialPropertyBlock();
            jitter = new System.Random(StableHash(lookId));
            flicker = GetComponent<RendererFlicker>();
            if (mouth != null) {
                mouthRestPos = mouth.localPosition;
                mouthRestScale = mouth.localScale;
            }
        }

        // Colours, height and accessory from the look (ViewFactory, MenuBuilder). Null keeps the defaults.
        public void Configure(PassengerLookDefinition look) {
            Capture();
            GreyboxLook greybox = look != null ? look.greybox : new GreyboxLook();
            lookId = look != null ? look.id : "";
            bodyColor = greybox.bodyColor;
            headColor = greybox.headColor;
            if (rig != null) {
                rig.localScale = Vector3.one * Mathf.Clamp(greybox.heightScale, 0.95f, 1.05f);
            }
            for (int i = 0; i < accessories.Length; i++) {
                if (accessories[i] != null) {
                    accessories[i].SetActive((int)greybox.accessory == i + 1);
                }
            }
            // Idle bobs out of step with each other; derived from the look, so it's deterministic
            bobPhase = look != null ? (StableHash(look.id) & 0x3ff) / 1024f : 0f;
            jitter = new System.Random(StableHash(lookId));
            ApplyColours(0f);
        }

        // string.GetHashCode isn't stable across runtimes
        static int StableHash(string text) {
            int sum = 17;
            for (int i = 0; i < text.Length; i++) {
                sum = sum * 31 + text[i];
            }
            return sum & 0x7fffffff;
        }

        void ApplyColours(float reveal) {
            Paint(bodyRenderers, Color.Lerp(bodyColor, RevealRed, reveal));
            Paint(headRenderers, Color.Lerp(headColor, RevealRed, reveal));
        }

        void Paint(Renderer[] renderers, Color color) {
            if (block == null) {
                block = new MaterialPropertyBlock();
            }
            for (int i = 0; i < renderers.Length; i++) {
                if (renderers[i] == null) {
                    continue;
                }
                renderers[i].GetPropertyBlock(block);
                block.SetColor("_BaseColor", color);
                renderers[i].SetPropertyBlock(block);
            }
        }

        // ------------------------------------------------------------ PassengerViewBase

        public override void SetPose(PassengerPose next) {
            pose = next;
            ApplyPose(pose == PassengerPose.Seated && Tell(TellId.TelegraphStand) <= 0f);
        }

        void ApplyPose(bool seated) {
            if (body != null) {
                body.localPosition = seated ? SeatedBodyPos : StandingBodyPos;
                body.localScale = seated ? SeatedBodyScale : StandingBodyScale;
            }
            if (headPivot != null) {
                headPivot.localPosition = seated ? SeatedHeadPos : StandingHeadPos;
            }
            if (shoulders != null) {
                shoulders.localPosition = new Vector3(0f, seated ? SeatedShoulderY : StandingShoulderY, 0f);
            }
        }

        public override void SetLocomotion(float metresPerSecond) {
            locomotion = Mathf.Max(0f, metresPerSecond);
        }

        public override void SetTell(TellId tell, float intensity01) {
            int slot = Slot(tell);
            if (slot < 0) {
                return;
            }
            float value = Mathf.Clamp01(intensity01);
            float before = tells[slot];
            tells[slot] = value;
            switch (tell) {
                case TellId.MimicFlicker:
                    if (Flicker != null) {
                        Flicker.SetFlicker(value);
                    }
                    break;
                case TellId.MimicReveal:
                    if (Flicker != null) {
                        Flicker.SetFastBlink(value > 0f);
                    }
                    break;
                case TellId.TelegraphStand:
                    if ((before > 0f) != (value > 0f)) {
                        SetPose(pose);
                    }
                    break;
            }
        }

        public override void SetLookAt(Transform target, float weight01) {
            lookTarget = target;
            lookWeight = Mathf.Clamp01(weight01);
        }

        public override void PlayReaction(ReactionId reaction) {
            float now = Time.time;
            switch (reaction) {
                case ReactionId.Flinch:
                    flinchUntil = now + FlinchSeconds;
                    break;
                case ReactionId.LookAround:
                    lookAroundStart = now;
                    break;
                case ReactionId.TurnToCamera:
                    // Snaps to the look target (the scare sets it to the camera first) and holds
                    if (lookTarget != null) {
                        headTrack = DesiredTrack();
                    }
                    turnHoldUntil = now + TurnHoldSeconds;
                    break;
            }
        }

        public override void PlayDeath() {
            if (deathStart < 0f) {
                deathStart = Time.time;
            }
        }

        public override void SetShadowCasting(bool on) {
            UnityEngine.Rendering.ShadowCastingMode mode = on
                ? UnityEngine.Rendering.ShadowCastingMode.On
                : UnityEngine.Rendering.ShadowCastingMode.Off;
            foreach (Renderer part in GetComponentsInChildren<Renderer>(true)) {
                part.shadowCastingMode = mode;
            }
        }

        public override void SetRenderLayer(int layer) {
            SetLayer(transform, layer);
        }

        static void SetLayer(Transform node, int layer) {
            node.gameObject.layer = layer;
            for (int i = 0; i < node.childCount; i++) {
                SetLayer(node.GetChild(i), layer);
            }
        }

        public override void SetVisible(bool visible) {
            if (Flicker != null) {
                Flicker.SetVisible(visible);
                return;
            }
            foreach (Renderer part in GetComponentsInChildren<Renderer>(true)) {
                part.enabled = visible;
            }
        }

        // The factory adds the flicker after Awake
        RendererFlicker Flicker {
            get {
                if (flicker == null) {
                    flicker = GetComponent<RendererFlicker>();
                }
                return flicker;
            }
        }

        public float Tell(TellId tell) {
            int slot = Slot(tell);
            return slot >= 0 ? tells[slot] : 0f;
        }

        static int Slot(TellId tell) {
            switch (tell) {
                case TellId.HeadTrack: return 0;
                case TellId.Stillness: return 1;
                case TellId.EyesWide: return 2;
                case TellId.WhisperLean: return 3;
                case TellId.MouthWhisper: return 4;
                case TellId.JawStretch: return 5;
                case TellId.MimicFlicker: return 6;
                case TellId.MimicReveal: return 7;
                case TellId.TelegraphStand: return 8;
                case TellId.AngelWeep: return 9;
                case TellId.AngelReach: return 10;
                case TellId.DecoyNodOff: return 11;
                case TellId.DecoyPhoneGlow: return 12;
                case TellId.DecoyMutter: return 13;
                case TellId.DecoyFacingBackwards: return 14;
                case TellId.DecoyHoodUp: return 15;
                default: return -1;
            }
        }

        // ------------------------------------------------------------------ frame

        void LateUpdate() {
            float dt = Time.deltaTime;
            float now = Time.time;
            UpdateBody(now);
            UpdateHead(dt, now);
            UpdateFace(now);
            UpdateArms();
            UpdateReveal();
        }

        void UpdateBody(float now) {
            if (rig != null) {
                rig.localRotation = Tell(TellId.DecoyFacingBackwards) >= 0.5f ? Quaternion.Euler(0f, 180f, 0f) : Quaternion.identity;
            }
            if (bodyPivot == null) {
                return;
            }
            float bob = BobAmplitude * (1f - Tell(TellId.Stillness)) * Mathf.Sin((now * BobHz + bobPhase) * Mathf.PI * 2f);
            if (locomotion > 0.1f) {
                bob += WalkBobAmplitude * Mathf.Abs(Mathf.Sin(now * WalkBobHz * Mathf.PI));
            }
            float pitch = TelegraphLean * Tell(TellId.TelegraphStand);
            float roll = -MaxLean * Tell(TellId.WhisperLean) * LeanSide();
            if (deathStart >= 0f) {
                // Falls over sideways and stays down
                roll = Mathf.Lerp(roll, 85f, Mathf.Clamp01((now - deathStart) / DeathSeconds));
            }
            bodyPivot.localPosition = new Vector3(0f, bob, 0f);
            bodyPivot.localRotation = Quaternion.Euler(pitch, 0f, roll);
            float squash = now < flinchUntil ? 0.9f : 1f;
            bodyPivot.localScale = new Vector3(1f, squash, 1f);
        }

        // +1 leans right, −1 left: toward the look target's side
        float LeanSide() {
            if (lookTarget == null) {
                return 1f;
            }
            float x = transform.InverseTransformPoint(lookTarget.position).x;
            return x >= 0f ? 1f : -1f;
        }

        void UpdateHead(float dt, float now) {
            if (headPivot == null) {
                return;
            }
            float weight = Mathf.Max(lookWeight, Tell(TellId.HeadTrack));
            bool holding = now < turnHoldUntil;
            Quaternion desired = lookTarget != null && (weight > 0f || holding) ? DesiredTrack() : Quaternion.identity;
            if (holding && lookTarget != null) {
                headTrack = desired;
            }else {
                headTrack = Quaternion.RotateTowards(headTrack, desired, HeadTurnSpeed * dt);
            }
            float pitchDown = Mathf.Max(NodPitch * Tell(TellId.DecoyNodOff), WeepPitch * Tell(TellId.AngelWeep));
            float lookAroundYaw = 0f;
            if (lookAroundStart >= 0f) {
                float t = (now - lookAroundStart) / LookAroundSeconds;
                if (t >= 1f) {
                    lookAroundStart = -1f;
                }else {
                    lookAroundYaw = 45f * Mathf.Sin(t * Mathf.PI * 2f);
                }
            }
            if (deathStart >= 0f) {
                pitchDown = Mathf.Max(pitchDown, 50f);
            }
            headPivot.localRotation = headTrack * Quaternion.Euler(pitchDown, lookAroundYaw, 0f);
            if (hood != null) {
                bool hooded = Tell(TellId.DecoyHoodUp) > 0f;
                if (hood.activeSelf != hooded) {
                    hood.SetActive(hooded);
                }
            }
        }

        // The MVP StaringMonster math, in the view's space around the head pivot
        Quaternion DesiredTrack() {
            Vector3 toTarget = transform.InverseTransformPoint(lookTarget.position) - headPivot.localPosition;
            float yaw = Mathf.Clamp(Mathf.Atan2(toTarget.x, toTarget.z) * Mathf.Rad2Deg, -YawLimit, YawLimit);
            float flat = new Vector2(toTarget.x, toTarget.z).magnitude;
            float pitch = Mathf.Clamp(-Mathf.Atan2(toTarget.y, flat) * Mathf.Rad2Deg, -PitchLimit, PitchLimit);
            return Quaternion.Euler(pitch, yaw, 0f);
        }

        void UpdateFace(float now) {
            if (eyes != null) {
                float wide = Tell(TellId.EyesWide);
                bool show = wide > 0f;
                if (eyes.gameObject.activeSelf != show) {
                    eyes.gameObject.SetActive(show);
                }
                for (int i = 0; i < eyes.childCount; i++) {
                    eyes.GetChild(i).localScale = Vector3.one * MaxEyeScale * wide;
                }
            }
            if (mouth != null) {
                float mutter = Mathf.Max(Tell(TellId.MouthWhisper), Tell(TellId.DecoyMutter));
                Vector3 offset = Vector3.zero;
                float open = 1f;
                if (mutter > 0f) {
                    offset = new Vector3(0f, ((float)jitter.NextDouble() - 0.5f) * 2f * MouthJitter * mutter, 0f);
                    open += (float)jitter.NextDouble() * mutter;
                }
                float stretch = 1f + 2f * Tell(TellId.JawStretch);
                mouth.localPosition = mouthRestPos + offset;
                mouth.localScale = new Vector3(mouthRestScale.x, mouthRestScale.y * stretch * open, mouthRestScale.z);
            }
            if (phone != null) {
                float glow = Tell(TellId.DecoyPhoneGlow);
                bool show = glow > 0f;
                if (phone.gameObject.activeSelf != show) {
                    phone.gameObject.SetActive(show);
                }
                if (show) {
                    float pulse = 0.6f + 0.4f * Mathf.Sin(now * Mathf.PI * 2f * 0.5f);
                    phone.GetPropertyBlock(block);
                    block.SetColor("_EmissionColor", PhoneGlow * (1.5f * pulse * glow));
                    phone.SetPropertyBlock(block);
                }
            }
        }

        void UpdateArms() {
            float weep = Tell(TellId.AngelWeep);
            float reach = Tell(TellId.AngelReach);
            bool show = weep > 0f || reach > 0f;
            SetArm(armLeft, show, weep, reach, -1f);
            SetArm(armRight, show, weep, reach, 1f);
        }

        // The arm hangs from its shoulder pivot along −Y. Reach swings it forward (pitch −90);
        // weep raises it up in front of the face and in toward the centre.
        static void SetArm(Transform arm, bool show, float weep, float reach, float side) {
            if (arm == null) {
                return;
            }
            if (arm.gameObject.activeSelf != show) {
                arm.gameObject.SetActive(show);
            }
            if (!show) {
                return;
            }
            Quaternion reachRotation = Quaternion.Euler(-90f * reach, 0f, 0f);
            Quaternion weepRotation = Quaternion.Euler(-135f, 0f, side * 25f);
            arm.localRotation = reach > 0f ? reachRotation : Quaternion.Slerp(Quaternion.identity, weepRotation, weep);
        }

        void UpdateReveal() {
            float reveal = Tell(TellId.MimicReveal);
            if (reveal > 0f || revealTinted) {
                ApplyColours(reveal);
                revealTinted = reveal > 0f;
            }
        }
    }
}
